package eyesee;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.metal.MetalLookAndFeel;
import java.awt.*;

public class OverlayGUI extends JFrame {

    private JPanel panel1;
    public ImageIcon icon;
    public JLabel label1;

    public OverlayGUI() {
        this.setContentPane(panel1);
        this.setTitle("EyeSee Overlay");
        this.setUndecorated(true);
//        this.setOpacity(0.5f);
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));

        this.panel1.setSize(800, 420);
        this.panel1.setOpaque(false);

        this.setContentPane(panel1);
        this.setLocationRelativeTo(null);

        this.icon = new ImageIcon(this.getClass().getResource("/overlay.png"));
//        Image image = this.icon.getImage();
//        Image newImage = image.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
//        this.icon = new ImageIcon(newImage);
        this.label1 = new JLabel(this.icon);
//        this.label1.setBounds(0, 0, 800, 420);
//        this.label1.setSize(800, 420);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBackground(new Color(-16777216));
        panel1.setEnabled(true);
        panel1.setForeground(new Color(-16777216));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
